import Head from 'next/head'
import Image from 'next/image'
import Feed from '../components/Feeds'
import Header from '../components/Header'


export default function Home() {
  return (
    <div className="bg-gray-50 h-screen overflow-y-scroll scrollbar-hide">
      <Head>
        <title>Instagram 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header></Header>
      <Feed></Feed>      
    </div>
  )
}
